del Game\*.class
del Server\*.class
del Game\ComputerFunctions\*.class
del Game\MMO\*.class
del Game\RunChallenge\*.class
del Assignments\*.class
del Applet\*.class
del Browser\*.class
del chat\messages\*.class
del chat\util\*.class
del chat\client\*.class
del chatServer\Assignments\*.class
del chatServer\chat\messages\*.class
del chatServer\chat\server\*.class
del chatServer\chat\util\*.class
del chatServer\com\plink\dolphinnet\*.class
del chatServer\Server\*.class
del chatServer\util\*.class
del com\plink\dolphinnet\*.class
del com\plink\dolphinnet\util\*.class
del com\plink\dolphinnet\assignments\*.class
del com\plink\Hack3D\*.class
del DBAdmin\*.class
del GUI\*.class
del HackerLogin\*.class
del HackerSearch\Assignments\*.class
del HackerSearch\Server\*.class
del HackerSearch\util\*.class
del Hackscript\*.class
del Hackscript\Model\*.class
del Hacktendo\*.class
del Hacktendo\Functions\*.class
del View\*.class
javac Game\*.java
javac Server\*.java
javac Game\ComputerFunctions\*.java
javac Game\MMO\*.java
javac Game\RunChallenge\*.java
javac Assignments\*.java
javac Applet\*.java
javac Browser\*.java
javac chat\messages\*.java
javac chat\util\*.java
javac chat\client\*.java
cd chatServer
javac Assignments\*.java
javac chat\messages\*.java
javac chat\server\*.java
javac chat\util\*.java
javac com\plink\dolphinnet\*.java
javac Server\*.java
javac util\*.java
cd ..
javac com\plink\dolphinnet\*.java
javac com\plink\dolphinnet\util\*.java
javac com\plink\dolphinnet\assignments\*.java
javac com\plink\Hack3D\*.java
javac DBAdmin\*.java
javac GUI\*.java
mkdir javax\servlet
xcopy javax\servletx\* javax\servlet\ /E /I /H
javac HackerLogin\*.java
rmdir javax\servlet /S
javac HackerSearch\Assignments\*.java
javac HackerSearch\Server\*.java
javac HackerSearch\util\*.java
javac Hackscript\*.java
javac Hackscript\Model\*.java
javac Hacktendo\*.java
javac Hacktendo\Functions\*.java
javac View\*.java