rm Game/*.class
rm Server/*.class
rm Game/ComputerFunctions/*.class
rm Game/MMO/*.class
rm Game/RunChallenge/*.class
rm Assignments/*.class
rm Applet/*.class
rm Browser/*.class
rm chat/messages/*.class
rm chat/util/*.class
rm chat/client/*.class
rm chatServer/Assignments/*.class
rm chatServer/chat/messages/*.class
rm chatServer/chat/server/*.class
rm chatServer/chat/util/*.class
rm chatServer/com/plink/dolphinnet/*.class
rm chatServer/Server/*.class
rm chatServer/util/*.class
rm com/plink/dolphinnet/*.class
rm com/plink/dolphinnet/util/*.class
rm com/plink/dolphinnet/assignments/*.class
rm com/plink/Hack3D/*.class
rm DBAdmin/*.class
rm GUI/*.class
rm HackerLogin/*.class
rm HackerSearch/Assignments/*.class
rm HackerSearch/Server/*.class
rm HackerSearch/util/*.class
rm Hackscript/*.class
rm Hackscript/Model/*.class
rm Hacktendo/*.class
rm Hacktendo/Functions/*.class
rm View/*.class
rm com/plink/dolphinstem/*.class
rm com/plink/dolphinstem/util/*.class
javac com/plink/dolphinstem/*.java
javac com/plink/dolphinstem/util/*.java
javac Game/*.java
javac Server/*.java
javac Game/ComputerFunctions/*.java
javac Game/MMO/*.java
javac Game/RunChallenge/*.java
javac Assignments/*.java
javac Applet/*.java
javac Browser/*.java
javac chat/messages/*.java
javac chat/util/*.java
javac chat/client/*.java
cd chatServer
javac Assignments/*.java
javac chat/messages/*.java
javac chat/server/*.java
javac chat/util/*.java
javac com/plink/dolphinnet/*.java
javac Server/*.java
javac util/*.java
cd ..
javac com/plink/dolphinnet/*.java
javac com/plink/dolphinnet/util/*.java
javac com/plink/dolphinnet/assignments/*.java
javac com/plink/Hack3D/*.java
javac DBAdmin/*.java
javac GUI/*.java
mkdir javax/servlet
cp -r javax/servletx/* javax/servlet/
javac HackerLogin/*.java
rm -r javax/servlet/
javac HackerSearch/Assignments/*.java
javac HackerSearch/Server/*.java
javac HackerSearch/util/*.java
javac Hackscript/*.java
javac Hackscript/Model/*.java
javac Hacktendo/*.java
javac Hacktendo/Functions/*.java
javac View/*.java