javac Applet/*.java
javac GUI/*.java
javac View/*.java
javac Assignments/*.java
javac Browser/*.java
javac Hacktendo/*.java
javac Hacktendo/Functions/*.java
javac Game/*.java
keytool -genkey -alias signFiles -keystore compstore -keypass awa878 -dname "cn=HackWars" -storepass awa878
jar cvf Hack.jar GUI/*.class Applet/*.class Assignments/*.class View/*.class Browser/*.class Game/HackerFile.class Game/ApplicationData.class Game/Port.class util/*.class chat/client/*.class chat/messages/*.class chat/util/*.class Hackscript/*.class Hackscript/Model/*.class Hacktendo/*.class Hacktendo/Functions/*.class jsyntaxpane/*.class jsyntaxpane/actions/*.class jsyntaxpane/lexers/*.class jsyntaxpane/components/*.class jsyntaxpane/syntaxkits/*.class jsyntaxpane/util/*.class META-INF/services/*.properties com/plink/dolphinnet/*.class com/plink/dolphinnet/assignments/*.class com/plink/dolphinnet/util/*.class com/plink/dolphinstem/*.class com/plink/Hack3D/*.class com/steadystate/css/*.class com/steadystate/css/dom/*.class com/steadystate/css/parser/*.class com/steadystate/css/parser/selectors/*.class org/antlr/runtime/*.class org/antlr/runtime/debug/*.class org/antlr/runtime/misc/*.class org/antlr/runtime/tree/*.class org/apache/axis/encoding/*.class org/apache/axis/encoding/ser/*.class org/apache/axis/encoding/ser/castor/*.class org/apache/ws/commons/serialize/*.class org/apache/ws/commons/util/*.class org/apache/xmlrpc/*.class org/apache/xmlrpc/client/*.class org/apache/xmlrpc/client/util/*.class org/apache/xmlrpc/common/*.class org/apache/xmlrpc/jaxb/*.class org/apache/xmlrpc/metadata/*.class org/apache/xmlrpc/parser/*.class org/apache/xmlrpc/serializer/*.class org/apache/xmlrpc/server/*.class org/apache/xmlrpc/util/*.class org/apache/xmlrpc/webserver/*.class org/apache/xmlrpc/webserver/*.properties org/lobobrowser/html/*.class org/lobobrowser/html/domimpl/*.class org/lobobrowser/html/gui/*.class org/lobobrowser/html/io/*.class org/lobobrowser/html/js/*.class org/lobobrowser/html/parser/*.class org/lobobrowser/html/renderer/*.class org/lobobrowser/html/style/*.class org/lobobrowser/html/test/*.class org/lobobrowser/js/*.class org/lobobrowser/util/*.class org/lobobrowser/util/gui/*.class org/lobobrowser/util/io/*.class org/mozilla/classfile/*.class org/mozilla/javascript/*.class org/mozilla/javascript/continuations/*.class org/mozilla/javascript/debug/*.class org/mozilla/javascript/jdk11/*.class org/mozilla/javascript/jdk13/*.class org/mozilla/javascript/optimizer/*.class org/mozilla/javascript/regexp/*.class org/mozilla/javascript/resources/*.properties org/mozilla/javascript/serialize/*.class org/mozilla/javascript/xml/*.class org/w3c/css/sac/*.class org/w3c/css/sac/helpers/*.class org/w3c/dom/*.class org/w3c/dom/css/*.class org/w3c/dom/html2/*.class org/w3c/dom/stylesheets/*.class org/w3c/dom/views/*.class net/* Game/MMO/*.class
jarsigner -keystore compstore -storepass awa878 -keypass awa878 Hack.jar signFiles
